[0m14:15:33.451396 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10715ef90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118b27890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118b27b10>]}


============================== 14:15:33.469235 | 4441b22e-dc06-41b0-8504-536e836fafe2 ==============================
[0m14:15:33.469235 [info ] [MainThread]: Running with dbt=1.10.11
[0m14:15:33.469497 [debug] [MainThread]: running dbt with arguments {'indirect_selection': 'eager', 'fail_fast': 'False', 'quiet': 'False', 'printer_width': '80', 'use_colors': 'True', 'invocation_command': 'dbt init', 'partial_parse': 'True', 'write_json': 'True', 'use_experimental_parser': 'False', 'warn_error': 'None', 'debug': 'False', 'empty': 'None', 'introspect': 'True', 'log_path': 'logs', 'target_path': 'None', 'static_parser': 'True', 'log_format': 'default', 'log_cache_events': 'False', 'profiles_dir': '/Users/aleksandr/.dbt', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'version_check': 'True', 'cache_selected_only': 'False'}
[0m14:15:33.497453 [info ] [MainThread]: Creating dbt configuration folder at /Users/aleksandr/.dbt
[0m14:16:30.483250 [debug] [MainThread]: Starter project path: /Users/aleksandr/Documents/Projects/StandUP_project/.venv/lib/python3.13/site-packages/dbt/include/starter_project
[0m14:16:30.501107 [info ] [MainThread]: 
Your new dbt project "standup_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:16:30.502963 [info ] [MainThread]: Setting up your profile.
[0m14:20:16.171024 [info ] [MainThread]: Profile standup_project written to /Users/aleksandr/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m14:20:16.179569 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 282.75555, "process_in_blocks": "0", "process_kernel_time": 0.366029, "process_mem_max_rss": "139608064", "process_out_blocks": "0", "process_user_time": 1.08899}
[0m14:20:16.180292 [debug] [MainThread]: Command `dbt init` succeeded at 14:20:16.180175 after 282.76 seconds
[0m14:20:16.180936 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118c69480>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1071f2450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118c888d0>]}
[0m14:20:16.181372 [debug] [MainThread]: Flushing usage events
[0m14:20:17.016817 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:20:31.991607 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103eb4050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104db3610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104db3890>]}


============================== 14:20:31.993861 | e8244ed9-9164-42bd-838f-54bd1b776899 ==============================
[0m14:20:31.993861 [info ] [MainThread]: Running with dbt=1.10.11
[0m14:20:31.994113 [debug] [MainThread]: running dbt with arguments {'warn_error': 'None', 'log_cache_events': 'False', 'partial_parse': 'True', 'indirect_selection': 'eager', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt debug', 'cache_selected_only': 'False', 'send_anonymous_usage_stats': 'True', 'use_colors': 'True', 'log_path': 'logs', 'target_path': 'None', 'no_print': 'None', 'profiles_dir': '/Users/aleksandr/.dbt', 'empty': 'None', 'quiet': 'False', 'write_json': 'True', 'log_format': 'default', 'printer_width': '80', 'debug': 'False', 'use_experimental_parser': 'False', 'introspect': 'True', 'fail_fast': 'False', 'version_check': 'True', 'static_parser': 'True'}
[0m14:20:32.005854 [info ] [MainThread]: dbt version: 1.10.11
[0m14:20:32.006037 [info ] [MainThread]: python version: 3.13.7
[0m14:20:32.006145 [info ] [MainThread]: python path: /Users/aleksandr/Documents/Projects/StandUP_project/.venv/bin/python3
[0m14:20:32.006243 [info ] [MainThread]: os info: macOS-15.6.1-arm64-arm-64bit-Mach-O
[0m14:20:32.030449 [info ] [MainThread]: Using profiles dir at /Users/aleksandr/.dbt
[0m14:20:32.030628 [info ] [MainThread]: Using profiles.yml file at /Users/aleksandr/.dbt/profiles.yml
[0m14:20:32.030731 [info ] [MainThread]: Using dbt_project.yml file at /Users/aleksandr/Documents/Projects/StandUP_project/dbt_project.yml
[0m14:20:32.031246 [info ] [MainThread]: adapter type: postgres
[0m14:20:32.031387 [info ] [MainThread]: adapter version: 1.9.1
[0m14:20:32.031502 [info ] [MainThread]: Configuration:
[0m14:20:32.031596 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m14:20:32.031690 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m14:20:32.031778 [info ] [MainThread]: Required dependencies:
[0m14:20:32.031895 [debug] [MainThread]: Executing "git --help"
[0m14:20:32.037831 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m14:20:32.038157 [debug] [MainThread]: STDERR: "b''"
[0m14:20:32.038285 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m14:20:32.038400 [info ] [MainThread]: Connection:
[0m14:20:32.038517 [info ] [MainThread]:   host: localhost
[0m14:20:32.038610 [info ] [MainThread]:   port: 5432
[0m14:20:32.038696 [info ] [MainThread]:   user: standup_project
[0m14:20:32.038782 [info ] [MainThread]:   database: standup_project
[0m14:20:32.038870 [info ] [MainThread]:   schema: standup_raw
[0m14:20:32.038955 [info ] [MainThread]:   connect_timeout: 10
[0m14:20:32.039041 [info ] [MainThread]:   role: None
[0m14:20:32.039126 [info ] [MainThread]:   search_path: None
[0m14:20:32.039210 [info ] [MainThread]:   keepalives_idle: 0
[0m14:20:32.039294 [info ] [MainThread]:   sslmode: None
[0m14:20:32.039376 [info ] [MainThread]:   sslcert: None
[0m14:20:32.039461 [info ] [MainThread]:   sslkey: None
[0m14:20:32.039544 [info ] [MainThread]:   sslrootcert: None
[0m14:20:32.039627 [info ] [MainThread]:   application_name: dbt
[0m14:20:32.039709 [info ] [MainThread]:   retries: 1
[0m14:20:32.039934 [info ] [MainThread]: Registered adapter: postgres=1.9.1
[0m14:20:32.079643 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m14:20:32.125874 [debug] [MainThread]: Using postgres connection "debug"
[0m14:20:32.126046 [debug] [MainThread]: On debug: select 1 as id
[0m14:20:32.126145 [debug] [MainThread]: Opening a new connection, currently in state init
[0m14:20:32.162619 [debug] [MainThread]: SQL status: SELECT 1 in 0.036 seconds
[0m14:20:32.163054 [debug] [MainThread]: On debug: Close
[0m14:20:32.163195 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m14:20:32.163328 [info ] [MainThread]: [31m1 check failed:[0m
[0m14:20:32.163430 [info ] [MainThread]: Project loading failed for the following reason:
 project path </Users/aleksandr/Documents/Projects/StandUP_project/dbt_project.yml> not found

[0m14:20:32.164585 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.20112179, "process_in_blocks": "0", "process_kernel_time": 0.134385, "process_mem_max_rss": "122585088", "process_out_blocks": "0", "process_user_time": 0.527407}
[0m14:20:32.164773 [debug] [MainThread]: Command `dbt debug` failed at 14:20:32.164735 after 0.20 seconds
[0m14:20:32.164904 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m14:20:32.165041 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10534ac40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1053a9d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104e699d0>]}
[0m14:20:32.165202 [debug] [MainThread]: Flushing usage events
[0m14:20:33.041655 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:16:33.296661 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c9d6cf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10da3fb10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10da3fc50>]}


============================== 15:16:33.313318 | 388480b5-6962-4b3f-809f-234ab07d26b9 ==============================
[0m15:16:33.313318 [info ] [MainThread]: Running with dbt=1.10.11
[0m15:16:33.313574 [debug] [MainThread]: running dbt with arguments {'debug': 'False', 'log_path': 'logs', 'log_cache_events': 'False', 'no_print': 'None', 'partial_parse': 'True', 'fail_fast': 'False', 'use_experimental_parser': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'printer_width': '80', 'empty': 'None', 'profiles_dir': '/Users/aleksandr/.dbt', 'version_check': 'True', 'send_anonymous_usage_stats': 'True', 'cache_selected_only': 'False', 'use_colors': 'True', 'invocation_command': 'dbt test', 'warn_error': 'None', 'static_parser': 'True', 'quiet': 'False', 'write_json': 'True', 'indirect_selection': 'eager', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default'}
[0m15:16:33.313844 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/aleksandr/Documents/Projects/StandUP_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:16:33.316276 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.05002379, "process_in_blocks": "0", "process_kernel_time": 0.260431, "process_mem_max_rss": "136249344", "process_out_blocks": "0", "process_user_time": 1.089409}
[0m15:16:33.316514 [debug] [MainThread]: Command `dbt test` failed at 15:16:33.316472 after 0.05 seconds
[0m15:16:33.316653 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10d957bb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10d9639b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10da98c00>]}
[0m15:16:33.316778 [debug] [MainThread]: Flushing usage events
[0m15:16:34.310407 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:19:23.314103 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1086bc050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1095b3610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1095b3750>]}


============================== 15:19:23.316277 | 35144516-1ecb-4c1e-8684-b7a6bec36b0d ==============================
[0m15:19:23.316277 [info ] [MainThread]: Running with dbt=1.10.11
[0m15:19:23.316508 [debug] [MainThread]: running dbt with arguments {'log_format': 'default', 'no_print': 'None', 'fail_fast': 'False', 'log_cache_events': 'False', 'quiet': 'False', 'write_json': 'True', 'profiles_dir': '/Users/aleksandr/.dbt', 'empty': 'None', 'debug': 'False', 'log_path': 'logs', 'partial_parse': 'True', 'target_path': 'None', 'version_check': 'True', 'introspect': 'True', 'use_experimental_parser': 'False', 'cache_selected_only': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'printer_width': '80', 'use_colors': 'True', 'invocation_command': 'dbt test', 'indirect_selection': 'eager', 'warn_error': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:19:23.316734 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/aleksandr/Documents/Projects/StandUP_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:19:23.318198 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.032940585, "process_in_blocks": "0", "process_kernel_time": 0.055896, "process_mem_max_rss": "107610112", "process_out_blocks": "0", "process_user_time": 0.471995}
[0m15:19:23.318376 [debug] [MainThread]: Command `dbt test` failed at 15:19:23.318340 after 0.03 seconds
[0m15:19:23.318488 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109614180>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1095e2450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109445bf0>]}
[0m15:19:23.318604 [debug] [MainThread]: Flushing usage events
[0m15:19:24.018240 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:59:11.104323 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ac981a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10bae7890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10bae7d90>]}


============================== 17:59:11.106608 | 36087b04-6a51-42c9-935d-0237001c188b ==============================
[0m17:59:11.106608 [info ] [MainThread]: Running with dbt=1.10.13
[0m17:59:11.106842 [debug] [MainThread]: running dbt with arguments {'quiet': 'False', 'write_json': 'True', 'use_colors': 'True', 'warn_error': 'None', 'introspect': 'True', 'cache_selected_only': 'False', 'debug': 'False', 'static_parser': 'True', 'log_path': 'logs', 'invocation_command': 'dbt test --select core', 'version_check': 'True', 'use_experimental_parser': 'False', 'log_cache_events': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'fail_fast': 'False', 'printer_width': '80', 'target_path': 'None', 'indirect_selection': 'eager', 'send_anonymous_usage_stats': 'True', 'partial_parse': 'True', 'profiles_dir': '/Users/aleksandr/.dbt', 'empty': 'None', 'log_format': 'default'}
[0m17:59:11.107083 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/aleksandr/Documents/Projects/StandUP_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:59:11.108895 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.031852335, "process_in_blocks": "0", "process_kernel_time": 0.093135, "process_mem_max_rss": "108298240", "process_out_blocks": "0", "process_user_time": 0.457255}
[0m17:59:11.109102 [debug] [MainThread]: Command `dbt test` failed at 17:59:11.109063 after 0.03 seconds
[0m17:59:11.109225 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10bb4c2b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10bb16690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b972140>]}
[0m17:59:11.109341 [debug] [MainThread]: Flushing usage events
[0m17:59:12.045335 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:12:03.164275 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1080a01a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108eef890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108eefd90>]}


============================== 19:12:03.166624 | 3908fce1-0700-4467-8765-fb4f6e9d7f91 ==============================
[0m19:12:03.166624 [info ] [MainThread]: Running with dbt=1.10.13
[0m19:12:03.166858 [debug] [MainThread]: running dbt with arguments {'log_cache_events': 'False', 'log_path': 'logs', 'use_colors': 'True', 'profiles_dir': '/Users/aleksandr/.dbt', 'send_anonymous_usage_stats': 'True', 'empty': 'False', 'use_experimental_parser': 'False', 'printer_width': '80', 'cache_selected_only': 'False', 'warn_error': 'None', 'static_parser': 'True', 'write_json': 'True', 'quiet': 'False', 'target_path': 'None', 'partial_parse': 'True', 'version_check': 'True', 'introspect': 'True', 'indirect_selection': 'eager', 'debug': 'False', 'fail_fast': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'log_format': 'default', 'invocation_command': 'dbt run', 'no_print': 'None'}
[0m19:12:03.167077 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/aleksandr/Documents/Projects/StandUP_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:12:03.168245 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.030482333, "process_in_blocks": "0", "process_kernel_time": 0.076677, "process_mem_max_rss": "108118016", "process_out_blocks": "0", "process_user_time": 0.443726}
[0m19:12:03.168433 [debug] [MainThread]: Command `dbt run` failed at 19:12:03.168402 after 0.03 seconds
[0m19:12:03.168544 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108f542b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108f1e690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108d76140>]}
[0m19:12:03.168652 [debug] [MainThread]: Flushing usage events
[0m19:12:03.843386 [debug] [MainThread]: An error was encountered while trying to flush usage events
